StLouisSitesMVC/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSitesMVC.Models
{
    public class Location : IModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string County { get; set; }

        public IList<Review> Reviews { get; set; }
        public IList<LocationCategory> LocationCategories { get; set; }
       
        

    }
}

StLouisSitesMVC/ViewModels/Location/LocationCategoriesCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSitesMVC.ViewModels.Location
{
    public class LocationCategoriesCreateViewModel
    {
        public int Id { get; set; }
        public bool Selected { get; set; }
        public string CategoryName { get; set; }
    }
}

StLouisSitesMVC/ViewModels/Location/LocationCreateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using StLouisSitesMVC.Data;
using StLouisSitesMVC.Models;
using StLouisSitesMVC.ViewModels.Categories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSitesMVC.ViewModels.Location
{
    

    public class LocationCreateViewModel
    {

        [Required(ErrorMessage ="You must enter a name!!!")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Description must be between 2 and 200 characters")]
        [MinLength(2)]
        [MaxLength(200)]
        public string Description { get; set; }
        [Required(ErrorMessage ="Enter an address!")]
        public string Address { get; set; }
        [Required(ErrorMessage ="You must select a county!")]
        public string County { get; set; }
        public List<int> CategoryIds { get; set; }
        public List<LocationCategoriesCreateViewModel> Categories { get; set; }
       

        //public static int CreateLocation(ApplicationDbContext context, LocationCreateViewModel locationViewModel)
        //{
        //    Models.Location location = new Models.Location();
        //    {
        //        location.Name = locationViewModel.Name;
        //        location.Description = locationViewModel.Description;
        //        location.Address = locationViewModel.Address;
        //        location.County = locationViewModel.County;
        //    }
        //    context.Add(location);

        //    context.SaveChanges();

        //    return location.Id;


        //}

        public LocationCreateViewModel() { }

        public LocationCreateViewModel(ApplicationDbContext context)
        {
            List<int> CategoryIds = new List<int>();

            this.Categories = context.Categories.Select(category => new LocationCategoriesCreateViewModel {
                CategoryName = category.CategoryName,
                Id = category.Id

            }).ToList();
        }

        public void Persist(ApplicationDbContext context)
        {
            Models.Location location = new Models.Location
            {
                Name = this.Name,
                Description = this.Description,
                Address = this.Address,
                County = this.County,
                
            };
            context.Locations.Add(location);
            List<LocationCategory> locationCategories = CreateManyToManyRelationships(location.Id);
            location.LocationCategories = locationCategories;
            context.SaveChanges();
        }

        private List<LocationCategory> CreateManyToManyRelationships(int locationId)
        {
            return Categories.Where(cat => cat.Selected)
                .Select(cat => new LocationCategory { LocationId = locationId, CategoryId = cat.Id }).ToList();
        }


    }
}

StLouisSitesMVC/ViewModels/Location/LocationDetailsViewModel.cs
using StLouisSitesMVC.Data;
using StLouisSitesMVC.ViewModels.Review;
using StLouisSitesMVC.ViewModels.Categories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StLouisSitesMVC.Models;
using Microsoft.EntityFrameworkCore;

namespace StLouisSitesMVC.ViewModels.Location
{
    public class LocationDetailsViewModel
    {
        private ApplicationDbContext context;
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<LocationCategory> LocationCategories { get; set;}
        public List<ReviewDetailsViewModel> ReviewDetailsViewModels { get; set; }
        public List<CategoryDetailsViewModel> CategoryDetailsViewModels { get; set; }
        //public string CategoryNames { get; set; }

        public static LocationDetailsViewModel GetLocationDetailsViewModel(ApplicationDbContext context, int locationId)
        {
            LocationDetailsViewModel locationDetailsViewModel = new LocationDetailsViewModel();

            Models.Location location = context.Locations
                .Include(l => l.LocationCategories)
                .FirstOrDefault(l => l.Id == locationId);


            List<Models.Review> reviews = context.Reviews
            .Where(r => r.LocationID == locationId)
            .ToList();

            var selectedCategories = context.LocationCategories
                .Where(locationCategory => locationCategory.LocationId == locationId)
                .ToList();

            List<Category> categories = context.Categories
            .ToList();
            
            selectedCategories.ForEach(selectedCategory => 
                selectedCategory.Category = categories.Single(category => 
                    category.Id == selectedCategory.CategoryId
                )
            );



            //IList<Models.LocationCategory> categories = location.LocationCategories;

            IList<ReviewDetailsViewModel> reviewDetailsViewModels = new List<ReviewDetailsViewModel>();
            foreach (Models.Review review in reviews)
            {
                ReviewDetailsViewModel reviewDetailsViewModel = new ReviewDetailsViewModel();
                reviewDetailsViewModel.Rating = review.Rating;
                reviewDetailsViewModel.Comment = review.Comment;
                reviewDetailsViewModels.Add(reviewDetailsViewModel);

            }



            List<CategoryDetailsViewModel> categoryDetailsViewModels = new List<CategoryDetailsViewModel>();
            foreach (Models.LocationCategory selectedCategory in selectedCategories)
            {
                CategoryDetailsViewModel categoryDetailsViewModel = new CategoryDetailsViewModel();
                categoryDetailsViewModel.Name = selectedCategory.Category.CategoryName;
                categoryDetailsViewModels.Add(categoryDetailsViewModel);

            }

            return new LocationDetailsViewModel()
            {
                Name = location.Name,
                Description = location.Description,
                Id = location.Id,
                ReviewDetailsViewModels = reviewDetailsViewModels.ToList(),
                CategoryDetailsViewModels = categoryDetailsViewModels.ToList()
            };
        }
    }
}

StLouisSitesMVC/ViewModels/Location/LocationEditViewModel.cs
using StLouisSitesMVC.Data;
using StLouisSitesMVC.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSitesMVC.ViewModels.Location
{
    public class LocationEditViewModel
    {
        private ApplicationDbContext context;
        public int Id { get; set; }
        [Required(ErrorMessage ="You must enter a location name!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Description must be between 2 and 200 characters.")]
        [MinLength(2)]
        [MaxLength(200)]
        public string Description { get; set; }
        [Required(ErrorMessage ="Please enter an address!")]
        public string Address { get; set; }
        [Required(ErrorMessage ="You must select a county!")]
        public string County { get; set; }
        public List<int> CategoryIds { get; set; }
        public List<LocationCategoriesCreateViewModel> Categories { get; set; }

        public LocationEditViewModel() { }

        public LocationEditViewModel(int id, ApplicationDbContext context)
        {

            Models.Location location = context.Locations.
                Single(l => l.Id == id);

            Name = location.Name;
            Description = location.Description;
            Address = location.Address;
            County = location.County;

            var selectedCategories = context.LocationCategories.Where(locationCategory => locationCategory.LocationId == id);

            this.Categories = context.Categories.Select(category => new LocationCategoriesCreateViewModel
            {
                CategoryName = category.CategoryName,
                Id = category.Id,
                Selected = selectedCategories.Any(selectedCategory => selectedCategory.CategoryId == category.Id)

            }).ToList();

        }

        //public LocationEditViewModel(int id, ApplicationDbContext context)
        //{
        //    this.Categories = context.Categories.Select(category => new LocationCategoriesCreateViewModel
        //    {
        //        CategoryName = category.CategoryName,
        //        Id = category.Id

        //    }).ToList();
        //}

        public void Persist(int id, ApplicationDbContext context)
        {
            Models.Location location = new Models.Location()
            {
                Id = id,
                Name = this.Name,
                Description = this.Description,
                Address = this.Address,
                County = this.County
            };
            context.Update(location);
            List<LocationCategory> locationCategories = CreateManyToManyRelationships(location.Id);
            location.LocationCategories = locationCategories;
            var locationCategoriesToDelete = context.LocationCategories.Where(lc => lc.LocationId == id);
            context.RemoveRange(locationCategoriesToDelete);

            context.SaveChanges();

        }

        private List<LocationCategory> CreateManyToManyRelationships(int locationId)
        {
            return Categories.Where(cat => cat.Selected)
                .Select(cat => new LocationCategory { LocationId = locationId, CategoryId = cat.Id }).ToList();
        }
    }
}

StLouisSitesMVC/ViewModels/Location/LocationListItemViewModel.cs
using Microsoft.EntityFrameworkCore;
using StLouisSitesMVC.Data;
using StLouisSitesMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSitesMVC.ViewModels.Location
{
    public class LocationListItemViewModel
    {
        public static List<LocationListItemViewModel> GetLocationListItemViewModel(ApplicationDbContext context)
        {
            List<Models.Location> locations = context.Locations
                .Include(l => l.Reviews)
                .ToList();


            List<LocationListItemViewModel> viewModelLocations = new List<LocationListItemViewModel>();
            foreach (Models.Location location in locations)
            {
                LocationListItemViewModel viewModel = new LocationListItemViewModel();
                viewModel.Id = location.Id;
                viewModel.Name = location.Name;
                viewModel.Description = location.Description;
                //viewModel.CategoryNames = GetCategoryNames(location, context);
                viewModel.Reviews = location.Reviews.ToList();
                viewModel.AverageRating = location.Reviews.Count > 0 ? Math.Round(location.Reviews.Average(x => x.Rating), 2).ToString() : "n/a";

                viewModelLocations.Add(viewModel);

            }
            return viewModelLocations;


        }

        //private static string GetCategoryNames(Models.Location location, ApplicationDbContext context)
        //{
        //    //List<string> categoryNames = location.LocationCategories
        //    //    .Select(lc => lc.Category)
        //    //    .Select(c => c.CategoryName)
        //    //    .ToList();

        //    List<int> categoryIds = location.LocationCategories.Select(lc => lc.CategoryId).ToList();
        //    List<Category> categories = context.Categories.Where(c => categoryIds.Contains(c.Id)).ToList();
        //    categoryNames = categories.Select(c => c.CategoryName).ToList();

        //    return String.Join(", ", categoryNames);
        //}

        private ApplicationDbContext context;
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CategoryNames { get; set; }
        public List<Models.Review> Reviews { get; set; }
        public string AverageRating { get; set; }




    }
    }

StLouisSitesMVC/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StLouisSitesMVC.Data;
using StLouisSitesMVC.Models;
using StLouisSitesMVC.ViewModels.Location;

namespace StLouisSitesMVC.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext context;

        public LocationController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<LocationListItemViewModel> viewModelLocations = LocationListItemViewModel.GetLocationListItemViewModel(context);
            return View(viewModelLocations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LocationCreateViewModel model = new LocationCreateViewModel(context);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(LocationCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                
                return View(model);
            }

            model.Persist(context);
            return RedirectToAction(actionName: nameof(Index));
        }
       

        public IActionResult Details(int id)
        {

            LocationDetailsViewModel locationDetailsViewModel = LocationDetailsViewModel.GetLocationDetailsViewModel(context, id);
            return View(locationDetailsViewModel);
        }

        //[HttpGet]
        //public IActionResult Edit(int id)
        //{
        //    return View(model: new LocationEditViewModel(id, context));
        //}

        //[HttpPost]
        //public IActionResult Edit(LocationEditViewModel locationEditViewModel, int id)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(new LocationEditViewModel());
        //    }
        //    locationEditViewModel.Persist(id, context);
        //    return RedirectToAction(actionName: nameof(Index));
        //}

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(new LocationEditViewModel(id, context));
        }

        [HttpPost]
        public IActionResult Edit(int id, LocationEditViewModel location)
        {
            if (!ModelState.IsValid)
            {

                return View(location);
            }

            location.Persist(id, context);
            return RedirectToAction(actionName: nameof(Index));
        }

    }
}

StLouisSitesMVC/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StLouisSitesMVC.Data;
using StLouisSitesMVC.Models;
using StLouisSitesMVC.ViewModels.Review;

namespace StLouisSitesMVC.Controllers
{
    public class ReviewController : Controller
    {
        private ApplicationDbContext context;

        public ReviewController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create(int locationID)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ReviewCreateViewModel reviewCreateViewModel)
        {
            int Id = ReviewCreateViewModel.GetReviewViewModel(context, reviewCreateViewModel);

            return RedirectToAction(controllerName: nameof(Location), actionName: nameof(Index));
        }

    }
}

StLouisSitesMVC/Views/Location/Create.cshtml
@model StLouisSitesMVC.ViewModels.Location.LocationCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input readonly asp-for="Id" class="form-control" value="0"/>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label">County</label>
                <select asp-for="County">
                    <option>      </option>
                    <option>St Louis City</option>
                    <option>St Louis County</option>
                    <option>St. Charles</option>
                </select>
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <ul>
                    @for (var i = 0; i < Model.Categories.Count; i++)
                    {
                        <li>
                            <input type="checkbox" asp-for="@Model.Categories[i].Selected" />
                            <label asp-for="@Model.Categories[i].Selected">@Model.Categories[i].CategoryName</label>
                            <input type="hidden" asp-for="@Model.Categories[i].Id" />
                            <input type="hidden" asp-for="@Model.Categories[i].CategoryName" />
                        </li>
                    }
                </ul> 
            </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSitesMVC/Views/Location/Delete.cshtml
@model StLouisSitesMVC.Models.Location

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StLouisSitesMVC/Views/Location/Details.cshtml
@model StLouisSitesMVC.ViewModels.Location.LocationDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<p>
    <a asp-controller="Review" asp-action="Create" asp-route-locationID="@Model.Id">Rate/Review</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>

                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            @*<td>
                @Html.DisplayFor(modelItem => Model.CategoryNames)
            </td>*@
        </tr>
    </thead>
    <tbody>

        <tr>

            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Description)
            </td>
            

            @*<div>
            <a asp-action="Index">Back to List</a>
        </div>*@




</tbody>


</table>
<h3>Selected Categories</h3>
<ul>
    
        @foreach (var item in Model.CategoryDetailsViewModels)
        {
            <li>
            @Html.DisplayFor(modelItem => item.Name)
            </li>
        }
    
</ul>
<br />
<h3>Ratings and Reviews</h3>
<br />

@foreach (var item in Model.ReviewDetailsViewModels)
{

    <li>
       Rating: @Html.DisplayFor(modelItem => item.Rating)
    </li>
    <ul>
        <li>
           Review: @Html.DisplayFor(modelItem => item.Comment)
        </li>
    </ul>

}
<br />

StLouisSitesMVC/Views/Location/Edit.cshtml
@model StLouisSitesMVC.ViewModels.Location.LocationEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Edit Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="ID" class="control-label"></label>*@
                <input hidden asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" value="@Model.Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" value="@Model.Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" value="@Model.Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <select asp-for="County">
                    <option>      </option>
                    <option>St Louis City</option>
                    <option>St Louis County</option>
                    <option>St. Charles</option>
                </select>
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <ul>
                    @for (var i = 0; i < Model.Categories.Count; i++)
                    {
                        <li>
                            <input type="checkbox" asp-for="@Model.Categories[i].Selected" />
                            <label asp-for="@Model.Categories[i].Selected">@Model.Categories[i].CategoryName</label>
                            <input type="hidden" asp-for="@Model.Categories[i].Id" />
                            <input type="hidden" asp-for="@Model.Categories[i].CategoryName" />
                        </li>
                    }
                </ul>
            </div>
            @*<div class="form-group">
            <label asp-for="CategoryIds" class="control-label"></label>
            @foreach (var category in Model.Categories)
            {
                <label>@category.CategoryName</label>
                @if (Model.CategoryIds.Contains(category.Id))
                {
                    <input type="checkbox" asp-for="CategoryIds" value="@category.Id" checked />
                }
                else
                {
                    <input type="checkbox" asp-for="CategoryIds" value="@category.Id" />
                }
            }
        </div>*@
            <div class="form-group">
                <button type="submit" value="Save" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSitesMVC/Views/Location/Index.cshtml
@model IEnumerable<StLouisSitesMVC.ViewModels.Location.LocationListItemViewModel>

@{
    ViewData["Title"] = "Locations";
}

<h1>Locations</h1>

<p>
    <a asp-action="Create">Add a new location</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Location
                @*@Html.DisplayNameFor(model => model.Name)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Average Rating
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    <a asp-controller="Location" asp-action="Details" asp-route-ID="@item.Id">@item.Name</a>
                    @*@Html.DisplayFor(modelItem => item.Name)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AverageRating)
                </td>
                <td>
                <td><a asp-controller="Review" asp-action="Create" asp-route-locationID="@item.Id">Rate/Review</a></td>
                <td>
                    |
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                </td>
            </tr>
        }
    </tbody>
</table>